---
title: "proj_test"
author: "Ning Hu"
date: "12/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("readxl")
FI <- read_excel("data.xlsx", sheet = "FI")
FI <- FI[-c(1,2)]
##my_data <- my_data[-c(1:6,8:10,31,42,53,64,66,69,93,96,122,170,191,193,203,205,207,209,256,258,284,295,299,308,314,316,336,338,356,358,371,373,378,385,390,392,397,401,457,459,539), ]
FI <- FI[c(460:538),]
FI <- FI[-c(36,73,79),]
FI <- FI[-72,]
FI.co2 = FI[c(1,2,6,14,25,26,30,31,32,33,34,35),]
FI.GHG = FI[c(37,38,42,50,61,62,66,67,68,69,70,71),]
FI.main = FI[c(72:75),]
dat <-t(FI)
FI.co2 <- t(FI.co2)
FI.GHG <- t(FI.GHG)
FI.main <- t(FI.main)

header.true <- function(df) {
  colnames(df) <- as.character(unlist(df[1,]))
  df = df[-1,]
  df = data.frame(df)
}
FI.co2 = header.true(FI.co2)
FI.GHG = header.true(FI.GHG)
FI.main = header.true(FI.main)

FI.co2$Fuel.Combustion.Activites = as.numeric(as.character(FI.co2$Fuel.Combustion.Activites))
FI.co2$Energy.Industries = as.numeric(as.character(FI.co2$Energy.Industries))
FI.co2$Manufacturing.Industries.and.Construction = as.numeric(as.character(FI.co2$Manufacturing.Industries.and.Construction))
FI.co2$Transport=as.numeric(as.character(FI.co2$Transport))
FI.co2$Commercial.Institutional = as.numeric(as.character(FI.co2$Commercial.Institutional))
FI.co2$Residential=as.numeric(as.character(FI.co2$Residential))
FI.co2$Industrial.Processes.and.Product.Use=as.numeric(as.character(FI.co2$Industrial.Processes.and.Product.Use))
FI.co2$Agriculture=as.numeric(as.character(FI.co2$Agriculture))
FI.co2$Waste.and.Others=as.numeric(as.character(FI.co2$Waste.and.Others))
FI.co2$Indirect.CO2=as.numeric(as.character(FI.co2$Indirect.CO2))
FI.co2$International.aviation=as.numeric(as.character(FI.co2$International.aviation))
FI.co2$International.maritime.transport=as.numeric(as.character(FI.co2$International.maritime.transport))

FI.GHG$Fuel.Combustion.Activites = as.numeric(as.character(FI.GHG$Fuel.Combustion.Activites))
FI.GHG$Energy.Industries = as.numeric(as.character(FI.GHG$Energy.Industries))
FI.GHG$Manufacturing.Industries.and.Construction = as.numeric(as.character(FI.GHG$Manufacturing.Industries.and.Construction))
FI.GHG$Transport=as.numeric(as.character(FI.GHG$Transport))
FI.GHG$Commercial.Institutional = as.numeric(as.character(FI.GHG$Commercial.Institutional))
FI.GHG$Residential=as.numeric(as.character(FI.GHG$Residential))
FI.GHG$Industrial.Processes.and.Product.Use=as.numeric(as.character(FI.GHG$Industrial.Processes.and.Product.Use))
FI.GHG$Agriculture=as.numeric(as.character(FI.GHG$Agriculture))
FI.GHG$Waste.and.Others=as.numeric(as.character(FI.GHG$Waste.and.Others))
FI.GHG$Indirect.GHG=as.numeric(as.character(FI.GHG$Indirect.CO2))
FI.GHG$International.aviation=as.numeric(as.character(FI.GHG$International.aviation))
FI.GHG$International.maritime.transport=as.numeric(as.character(FI.GHG$International.maritime.transport))

FI.main$GHG.national.total.emissions...index.1990 = as.numeric(as.character(FI.main$GHG.national.total.emissions...index.1990))
FI.main$Total.GHG.per.capita...t.CO2.eq..cap=as.numeric(as.character(FI.main$Total.GHG.per.capita...t.CO2.eq..cap))
FI.main$GHG.Intensity.of.fuel.commbustion...kg.CO2.eq..toe = as.numeric(as.character(FI.main$GHG.Intensity.of.fuel.commbustion...kg.CO2.eq..toe))
FI.main$Total.GHG...GDP.Intensity...ton.CO2.eq..M..10=as.numeric(as.character(FI.main$Total.GHG...GDP.Intensity...ton.CO2.eq..M..10))
FI.co2$year = c(1990:2017)
FI.GHG$year = c(1990:2017)
FI.main$year = c(1990:2017)
FI.transport = FI.co2$Transport
FI.manu = FI.co2$Manufacturing.Industries.and.Construction

```


```{r}
SK <- read_excel("data.xlsx", sheet = "SK")
SK <- SK[-c(1,2)]
##my_data <- my_data[-c(1:6,8:10,31,42,53,64,66,69,93,96,122,170,191,193,203,205,207,209,256,258,284,295,299,308,314,316,336,338,356,358,371,373,378,385,390,392,397,401,457,459,539), ]
SK <- SK[c(460:538),]
SK <- SK[-c(36,73,79),]
SK <- SK[-72,]
SK.co2 = SK[c(1,2,6,14,25,26,30,31,32,33,34,35),]
SK.GHG = SK[c(37,38,42,50,61,62,66,67,68,69,70,71),]
SK.main = SK[c(72:75),]
dat <-t(SK)
SK.co2 <- t(SK.co2)
SK.GHG <- t(SK.GHG)
SK.main <- t(SK.main)

header.true <- function(df) {
  colnames(df) <- as.character(unlist(df[1,]))
  df = df[-1,]
  df = data.frame(df)
}
SK.co2 = header.true(SK.co2)
SK.GHG = header.true(SK.GHG)
SK.main = header.true(SK.main)

SK.co2$Fuel.Combustion.Activites = as.numeric(as.character(SK.co2$Fuel.Combustion.Activites))
SK.co2$Energy.Industries = as.numeric(as.character(SK.co2$Energy.Industries))
SK.co2$Manufacturing.Industries.and.Construction = as.numeric(as.character(SK.co2$Manufacturing.Industries.and.Construction))
SK.co2$Transport=as.numeric(as.character(SK.co2$Transport))
SK.co2$Commercial.Institutional = as.numeric(as.character(SK.co2$Commercial.Institutional))
SK.co2$Residential=as.numeric(as.character(SK.co2$Residential))
SK.co2$Industrial.Processes.and.Product.Use=as.numeric(as.character(SK.co2$Industrial.Processes.and.Product.Use))
SK.co2$Agriculture=as.numeric(as.character(SK.co2$Agriculture))
SK.co2$Waste.and.Others=as.numeric(as.character(SK.co2$Waste.and.Others))
SK.co2$Indirect.CO2=as.numeric(as.character(SK.co2$Indirect.CO2))
SK.co2$International.aviation=as.numeric(as.character(SK.co2$International.aviation))
SK.co2$International.maritime.transport=as.numeric(as.character(SK.co2$International.maritime.transport))

SK.GHG$Fuel.Combustion.Activites = as.numeric(as.character(SK.GHG$Fuel.Combustion.Activites))
SK.GHG$Energy.Industries = as.numeric(as.character(SK.GHG$Energy.Industries))
SK.GHG$Manufacturing.Industries.and.Construction = as.numeric(as.character(SK.GHG$Manufacturing.Industries.and.Construction))
SK.GHG$Transport=as.numeric(as.character(SK.GHG$Transport))
SK.GHG$Commercial.Institutional = as.numeric(as.character(SK.GHG$Commercial.Institutional))
SK.GHG$Residential=as.numeric(as.character(SK.GHG$Residential))
SK.GHG$Industrial.Processes.and.Product.Use=as.numeric(as.character(SK.GHG$Industrial.Processes.and.Product.Use))
SK.GHG$Agriculture=as.numeric(as.character(SK.GHG$Agriculture))
SK.GHG$Waste.and.Others=as.numeric(as.character(SK.GHG$Waste.and.Others))
SK.GHG$Indirect.GHG=as.numeric(as.character(SK.GHG$Indirect.CO2))
SK.GHG$International.aviation=as.numeric(as.character(SK.GHG$International.aviation))
SK.GHG$International.maritime.transport=as.numeric(as.character(SK.GHG$International.maritime.transport))

SK.main$GHG.national.total.emissions...index.1990 = as.numeric(as.character(SK.main$GHG.national.total.emissions...index.1990))
SK.main$Total.GHG.per.capita...t.CO2.eq..cap=as.numeric(as.character(SK.main$Total.GHG.per.capita...t.CO2.eq..cap))
SK.main$GHG.Intensity.of.fuel.commbustion...kg.CO2.eq..toe = as.numeric(as.character(SK.main$GHG.Intensity.of.fuel.commbustion...kg.CO2.eq..toe))
SK.main$Total.GHG...GDP.Intensity...ton.CO2.eq..M..10=as.numeric(as.character(SK.main$Total.GHG...GDP.Intensity...ton.CO2.eq..M..10))
SK.co2$year = c(1990:2017)
SK.GHG$year = c(1990:2017)
SK.main$year = c(1990:2017)
SK.transport = SK.co2$Transport
SK.manu = SK.co2$Manufacturing.Industries.and.Construction

```


```{r}
FItable = cbind(FI.manu,rep("FI",28))
SKtable = cbind(SK.manu,rep("SK",28))
df.FISK = data.frame(rbind(FItable,SKtable))
names(df.FISK) = c("sample", "groups")
df.FISK$groups = as.factor(df.FISK$groups)
df.FISK$sample = as.double(as.character(df.FISK$sample))

## teat
mytest.1 = function(mydf){
  agg = aggregate(sample ~groups, data = mydf, FUN = mean)
  return(agg$sample[1] - agg$sample[2])
}
permute.sample.1 = function(){
  df.FISK$sample = df.FISK$sample[sample(nrow(df.FISK),nrow(df.FISK),replace=F)]
  return(mytest.1(df.FISK))
}
N = 1000
test.1 = replicate(N,permute.sample.1())
hist(test.1,breaks = 40, main = "Null distribution", prob=T,col = )
abline(v = mytest.1(df.FISK), col = 2, lwd = 2)
cat("P-value is",2*mean(test.1>mytest.1(df.FISK)))
```
```{r}
t.test(sample~groups,data = df.FISK,conf.level = 0.95, alternative="two.sided")
```

plot
```{r}
boxplot(sample~groups,data = df.FISK,
        ylab = 'CO2 emission',
        main = 'CO2 emission by Country')
```


Hypothesis Test for Finland and SK manufacturing mean.
```{r}
FI.manu.mean =  mean(FI.manu)
SK.manu.mean =  mean(SK.manu)
n=28
FI.manu.var = var(FI.manu)
SK.manu.var = var(SK.manu)

t_val = (FI.manu.mean-SK.manu.mean)/(FI.manu.var /n+SK.manu.var/n)^0.5
t.test()
```
```{r}
summary(SK.co2-FI.co2)
```

